### ISSUE TITLE
Bars visible next to folded regions

### ISSUE THREAD

**Issue by jamescherti** [jdtsmith/indent-bars#78]
When folding files using `(hide-sublevels 1)`, the indent-bars package displays vertical bars next to the folded region. These bars remain visible even though the code within the fold is collapsed. This behavior makes it unclear whether the folded section is collapsed correctly and visually clutters the buffer.

Here is the issue:
![image](https://github.com/user-attachments/assets/719c6be6-f85c-445e-8edb-211cd3f7525e)

The bars above should not appear next to the folded region.

**Steps to reproduce:**
1. Install [outline-indent](https://github.com/jamescherti/outline-indent.el).
2. Edit the following file:
```yaml
---

- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: "Directory {{ cfgdir }}"
      file:
        state: directory
        path: "{{ item }}"
        mode: '0755'
      loop:
        - "{{ cfgdir }}"

    - name: "Delete old configuration files"
      changed_when: false
      ansible.builtin.command:
        argv:
          - "del-config"

- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: "Directory {{ cfgdir }}"
      file:
        state: directory
        path: "{{ item }}"
        mode: '0755'
      loop:
        - "{{ cfgdir }}"

    - name: "Delete old configuration files"
      changed_when: false
      ansible.builtin.command:
        argv:
          - "del-config"
 ```
3. Activate outline indent with `(outline-indent-minor-mode)`.
4. Fold all folds of the following Yaml file using `(hide-sublevels 1)`.

**Comment by jdtsmith** [comment]
Does this resolve if blank-line display is disabled?

**Comment by jamescherti** [comment]
I tried:
```
commit 09f0798d546ee90f9bb4b730439670994ad354df (HEAD -> main, origin/main, origin/HEAD)
Author: JD Smith <93749+jdtsmith@users.noreply.github.com>
Date:   Sun Oct 6 18:30:10 2024 -0400
```

Same issue:
![image](https://github.com/user-attachments/assets/a4014b7c-ce2f-4b76-8324-c9caeb736a56)

**Comment by jamescherti** [comment]
It does not happen when I remove the blank line:
```
---

- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: "Directory {{ cfgdir }}"
      file:
        state: directory
        path: "{{ item }}"
        mode: '0755'
      loop:
        - "{{ cfgdir }}"

    - name: "Delete old configuration files"
      changed_when: false
      ansible.builtin.command:
        argv:
          - "del-config"
- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: "Directory {{ cfgdir }}"
      file:
        state: directory
        path: "{{ item }}"
        mode: '0755'
      loop:
        - "{{ cfgdir }}"

    - name: "Delete old configuration files"
      changed_when: false
      ansible.builtin.command:
        argv:
          - "del-config"
```
